export { default as GitHubIcon } from './GitHubIcon'
export { default as AlolonsoIcon } from './AlolonsoIcon'
export { default as LightIcon } from './LightIcon'
export { default as DarkIcon } from './DarkIcon'
export { default as ArrowIcon } from './ArrowIcon'
export { default as PokemonIcon } from './PokemonIcon'
